### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HowlessWasTaken** [MoeDevelops/autofisher#3]
Keeps saying searching screen

**Comment by MoeDevelops** [comment]
That is correct behaviour. I will add this to the readme later, sorry for not clarifying

**Comment by HowlessWasTaken** [comment]
> That is correct behaviour. I will add this to the readme later, sorry for not clarifying

But what do i do next

**Comment by MoeDevelops** [comment]
You fish in minecraft. You need to have subtitles on and the gui scale configured

**Comment by HowlessWasTaken** [comment]
> You fish in minecraft. You need to have subtitles on and the gui scale configured

Please put it in the readme, and gui scale... how do i know what to put, cuz in minecraft there for gui scale is small,large,normal... idk what the number 3 in config means

**Comment by HowlessWasTaken** [comment]
doesnt work, i have subtitles on and gui to 2 same as in config

**Comment by MoeDevelops** [comment]
try it out with optifine maybe. I can't log in to minecraft right now for some reason so I can't try it out without any mods

**Comment by HowlessWasTaken** [comment]
> try it out with optifine maybe. I can't log in to minecraft right now for some reason so I can't try it out without any mods

Its allright thanks for all the help, i needed it for a server but i found out the server changed stuff so there is no bobber effect or subtitle whatever it is u use to sense the fish, instead they have a notebox sound that makes a sound when a fish is on bait so i couldnt use it anyway unless i find something that triggers mouse action when it plays. Im not asking cuz i know ur busy, but if u think you could help me or have any idea on how i could autofish there i'd very much love that, so when your mc starts working go check akumamc.net, go to skyblock and run command /fish. Again thank you for your time :>

**Comment by MoeDevelops** [comment]
You should just have to replace the images in the folder with the noteblock sound subtitle, however it could trigger randomly, when the sound is used often on the server

**Comment by HowlessWasTaken** [comment]
> You should just have to replace the images in the folder with the noteblock sound subtitle, however it could trigger randomly, when the sound is used often on the server

So all of the 3 pictures i just replace with 1? And it should work?

**Comment by HowlessWasTaken** [comment]
I replaced the 3 .pngs with 1 .png of noteblock subtittle and config to 2 same as my gui scale and still nothing, do i have to be fullscreen or anything or myb its bugged cuz i have 2 monitors, idk what the problem is.

**Comment by MoeDevelops** [comment]
The name of the file has to be bobber[gui-scale].png. I did it with two monitors and i had no problems with it

**Comment by HowlessWasTaken** [comment]
> The name of the file has to be bobber[gui-scale].png. I did it with two monitors and i had no problems with it

Yeah i tried everything u said and suggested but it just wont work idk why thanks anyway.

**Comment by MoeDevelops** [comment]
A final thing you could try is in a singleplayer world, so that you have normal sounds (with the normal images)

**Comment by HowlessWasTaken** [comment]
> A final thing you could try is in a singleplayer world, so that you have normal sounds (with the normal images)

Yeah i tried everything with normal and still nothing, i only need it for that server. But its okay thanks
